#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
# SPDX-License-Identifier: Apache-2.0
#
# Gradle start up script for POSIX generated by "Gradle init".

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
APP_HOME=$(dirname "$(readlink -f "$0" 2>/dev/null || realpath "$0" 2>/dev/null || echo "$0")")

# Wrapper JAR location
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Download the wrapper jar if it is missing or empty (e.g. after a fresh clone)
if [ ! -f "$WRAPPER_JAR" ] || [ ! -s "$WRAPPER_JAR" ]; then
    echo "Downloading Gradle wrapper JAR…"
    WRAPPER_URL="https://services.gradle.org/distributions/gradle-8.9-wrapper.jar"
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$WRAPPER_URL" -o "$WRAPPER_JAR"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$WRAPPER_URL" -O "$WRAPPER_JAR"
    else
        echo "ERROR: curl or wget is required to download the Gradle wrapper." >&2
        exit 1
    fi
fi

# Resolve JAVA_HOME / java executable
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

if ! command -v "$JAVACMD" >/dev/null 2>&1; then
    echo "ERROR: JAVA_HOME is not set and 'java' was not found in PATH." >&2
    exit 1
fi

# Default JVM options (can be overridden by JAVA_OPTS / GRADLE_OPTS)
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    -classpath "$WRAPPER_JAR" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
